{"uuid": "721c66a5-cbbf-4579-ba11-363eec1b26a9", "children": ["ee9d78c1-11c4-48e7-99bd-760f7cdcaca7", "c30d5719-5765-44c2-9970-acdf89d51cb2"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 935, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\tests\\login_test.py\", line 13, in test_setup\n    driver = webdriver.Chrome(executable_path=\"../drivers/chromedriver.exe\")\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1557038306973, "stop": 1557038306976}], "start": 1557038306973, "stop": 1557038307324}