{"uuid": "821f4f58-d908-4fbb-bbba-f4faaaa38d33", "children": ["bc882817-b5f2-47a6-a51c-5d3a0f4dc272", "138bf697-b938-4106-888c-d33f0187b48a"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 935, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\tests\\login_test.py\", line 13, in test_setup\n    driver = webdriver.Chrome(executable_path=\"../drivers/chromedriver.exe\")\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1556994796174, "stop": 1556994796174}], "start": 1556994796174, "stop": 1556994796627}