{"uuid": "7164b459-8ceb-4e91-b803-b40f423c867f", "children": ["c136036a-3a08-4726-9e76-4a7b5f0dcd6e", "4aeed717-5388-4031-84f8-b5b9e48abe38"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 935, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\tests\\login_test.py\", line 13, in test_setup\n    driver = webdriver.Chrome(executable_path=\"../drivers/chromedriver.exe\")\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\Hp\\PycharmProjects\\AutomationFramework_1\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1556995030779, "stop": 1556995030779}], "start": 1556995030779, "stop": 1556995031138}